/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package soundpredictor;

import speakers.Speaker;

/**
 *
 * @author Gijs
 */
public class JPlotPanel extends javax.swing.JPanel {

    /**
     * Creates new form JPlotPanel
     */    
    
    public JPlotPanel() {
        initComponents();
    }

    public void setGraphWidth(float w){
        graph.width = w;
        graph.repaint();
    }
    
    public void setGraphHeight(float h){
        graph.height = h;
        graph.repaint();
    }
    
    public void setSpeakers(Speaker[] s){
        graph.spk = s;
        graph.repaint();
    }
    
    public void repaintGraph(){
        graph.repaint();
    }
    
    public void setUberParent(MainFrame p){
        graph.setUberParent(p);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph = new soundpredictor.LocationMap();
        options = new javax.swing.JPanel();
        origChkBx = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        axiChkBx = new javax.swing.JCheckBox();
        crsGrdChkBx = new javax.swing.JCheckBox();
        fnGrdChkBx = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout graphLayout = new javax.swing.GroupLayout(graph);
        graph.setLayout(graphLayout);
        graphLayout.setHorizontalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );
        graphLayout.setVerticalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        options.setBackground(new java.awt.Color(255, 255, 255));
        options.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        origChkBx.setBackground(new java.awt.Color(255, 255, 255));
        origChkBx.setText("Origin");
        origChkBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origChkBxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Display:");

        axiChkBx.setBackground(new java.awt.Color(255, 255, 255));
        axiChkBx.setText("Axes");
        axiChkBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axiChkBxActionPerformed(evt);
            }
        });

        crsGrdChkBx.setBackground(new java.awt.Color(255, 255, 255));
        crsGrdChkBx.setText("Course grid");
        crsGrdChkBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crsGrdChkBxActionPerformed(evt);
            }
        });

        fnGrdChkBx.setBackground(new java.awt.Color(255, 255, 255));
        fnGrdChkBx.setText("Fine grid");
        fnGrdChkBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnGrdChkBxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(optionsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(axiChkBx)
                            .addComponent(origChkBx)
                            .addComponent(crsGrdChkBx)
                            .addComponent(fnGrdChkBx))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(origChkBx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(axiChkBx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crsGrdChkBx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fnGrdChkBx)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void origChkBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origChkBxActionPerformed
        graph.origin = origChkBx.isSelected();
        graph.repaint();
    }//GEN-LAST:event_origChkBxActionPerformed

    private void axiChkBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axiChkBxActionPerformed
        graph.axes = axiChkBx.isSelected();
        graph.repaint();
    }//GEN-LAST:event_axiChkBxActionPerformed

    private void crsGrdChkBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crsGrdChkBxActionPerformed
        graph.courseGrd = crsGrdChkBx.isSelected();
        graph.repaint();
    }//GEN-LAST:event_crsGrdChkBxActionPerformed

    private void fnGrdChkBxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnGrdChkBxActionPerformed
        graph.fineGrd = fnGrdChkBx.isSelected();
        graph.repaint();
    }//GEN-LAST:event_fnGrdChkBxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox axiChkBx;
    private javax.swing.JCheckBox crsGrdChkBx;
    private javax.swing.JCheckBox fnGrdChkBx;
    private soundpredictor.LocationMap graph;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel options;
    private javax.swing.JCheckBox origChkBx;
    // End of variables declaration//GEN-END:variables


}
